---
- name: Configure Full ZTP Host - Austin Site
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    sat_url: "https://nuc6.aus.redhat.com"
    sat_org: "Red Hat"
    sat_domain: "aus.redhat.com"

  tasks:
    - name: Create Managed Host in Satellite
      redhat.satellite.host:
        server_url: "{{ sat_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        name: "{{ vm_hostname }}.{{ sat_domain }}"
        organization: "{{ sat_org }}"
        location: "Austin"
        ip: "{{ ip_address }}"
        mac: "{{ mac_address }}"
        hostgroup: "{{ hostgroup }}"
          #root_pass: "RedHat123!"
        managed: true     # Enable orchestration (DHCP/DNS/TFTP)
        build: true       # Put host in 'Pending Installation' mode
        state: present
      delegate_to: localhost

    - name: Wait for the host to complete provisioning
      redhat.satellite.host_info:
        server_url: "{{ sat_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        name: "{{ vm_hostname }}.{{ sat_domain }}"
      register: host_details
      until:
        - host_details.host is not none
        - host_details.host.build == false
      retries: 60
      delay: 60
      delegate_to: localhost
