---
- name: Configure Full ZTP Host - Austin Site
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Use your survey variables here
    sat_url: "https://nuc6.aus.redhat.com"
    sat_org: "Red Hat" # Ensure this is the LABEL
    sat_domain: "aus.redhat.com"
    target_os: "RHEL 9.6" # Ensure this is the exact OS Name

  tasks:
    - name: Create Managed Host in Satellite
      redhat.satellite.host:
        server_url: "{{ sat_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        name: "{{ vm_hostname }}.{{ sat_domain }}"
        organization: "{{ sat_org }}"
        location: "Austin"
        ip: "{{ ip_address }}"
        mac: "{{ mac_address }}"
        hostgroup: "Austin-ZTP"
        managed: false
        state: present
      delegate_to: localhost
        #        domain: "{{ sat_domain }}"
        #        subnet: "Austin Subnet"
        #        operatingsystem: "{{ target_os }}"
        #        architecture: "x86_64"
        #        pxe_loader: "PXELinux BIOS"
        #        provision_method: "build"
        #        managed: false
        #        build: false
        #      delegate_to: localhost

    - name: Wait for the host to complete provisioning
      redhat.satellite.host_info:
        server_url: "{{ sat_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        name: "{{ vm_hostname }}.{{ sat_domain }}"
      register: host_details
      # Fails quickly if the host wasn't created
      failed_when: host_details.host is none
      until: 
        - host_details.host is not none
        - host_details.host.build == false
      retries: 45
      delay: 60
      delegate_to: localhost
