---
- name: Configure Full ZTP Host - Austin Site
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # ONLY things that change per-run go in the Survey
    target_mac: "{{ mac_address }}"
    target_ip: "{{ ip_address }}"
    target_hostname: "{{ vm_hostname }}"

    # Austin Environment Constants
    sat_org: "Red_Hat"
    sat_location: "Austin"
    sat_domain: "aus.redhat.com"
    sat_subnet: "Austin Subnet"

    target_os: "RedHat 9.6"
    target_arch: "x86_64"
    kickstart_template: "Kickstart default"
    pxe_template: "PXELinux default local boot"

  tasks:
    - name: Create Managed Host in Satellite
      redhat.satellite.host:
        validate_certs: false
        name: "{{ target_hostname }}.{{ sat_domain }}"
        organization: "{{ sat_org }}"
        location: "{{ sat_location }}"
        ip: "{{ target_ip }}"
        mac: "{{ target_mac }}"
        domain: "{{ sat_domain }}"
        subnet: "{{ sat_subnet }}"
        operatingsystem: "{{ target_os }}"
        architecture: "{{ target_arch }}"
        pxelinux_template: "{{ pxe_template }}"
        provisioning_template: "{{ kickstart_template }}"
        managed: true
        build: true
        parameters:
          - name: "package_upgrade"
            value: "false"
          - name: "additional_packages"
            value: "rsync bash-completion"
      delegate_to: localhost

    - name: Wait for the host to complete provisioning
      redhat.satellite.host_info:
        validate_certs: false
        name: "{{ target_hostname }}.{{ sat_domain }}"
      register: host_details
      until: host_details.host.build == false
      retries: 45
      delay: 60
      delegate_to: localhost
