---
- name: Configure Full ZTP Host - Austin Site
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # From AAP Survey
    target_mac: "{{ mac_address }}"
    target_ip: "{{ ip_address }}"
    target_hostname: "{{ vm_hostname }}"
    sat_url: "nuc6.aus.redhat.com"

    # Austin Environment Constants
    sat_org: "Red_Hat"
    sat_location: "Austin"
    sat_domain: "aus.redhat.com"
    sat_subnet: "Austin Subnet"
    target_os: "RedHat 9.6"
    target_arch: "x86_64"
    target_pxe_loader: "PXELinux BIOS"

  pre_tasks:
    - name: Verify IP is not already assigned in Satellite
      redhat.satellite.host_info:
        server_url: "{{ sat_url }}"
        validate_certs: false
        search: "ip = {{ target_ip }}"
      register: ip_search
      # Only runs if the previous task actually contacted the server
      failed_when:
        - ip_search.hosts is defined
        - ip_search.hosts | length > 0
      delegate_to: localhost

  tasks:
    - name: Create Managed Host in Satellite
      redhat.satellite.host:
        server_url: "{{ sat_url }}"
        validate_certs: false
        name: "{{ target_hostname }}.{{ sat_domain }}"
        organization: "{{ sat_org }}"
        location: "{{ sat_location }}"
        ip: "{{ target_ip }}"
        mac: "{{ target_mac }}"
        domain: "{{ sat_domain }}"
        subnet: "{{ sat_subnet }}"
        operatingsystem: "{{ target_os }}"
        architecture: "{{ target_arch }}"
        pxe_loader: "{{ target_pxe_loader }}"
        provision_method: "build"
        managed: true
        build: true
        parameters:
          - name: "package_upgrade"
            value: "false"
          - name: "additional_packages"
            value: "rsync bash-completion"
      delegate_to: localhost

    - name: Wait for the host to complete provisioning
      redhat.satellite.host_info:
        server_url: "{{ sat_url }}"
        validate_certs: false
        name: "{{ target_hostname }}.{{ sat_domain }}"
      register: host_details
      until:
        - host_details.host is defined
        - host_details.host.build == false
      retries: 45
      delay: 60
      delegate_to: localhost
